### ISSUE TITLE
Switch static code analysis from jshint to eslint

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#105]
Switch static code analysis from [jshint](http://jshint.com/) to [eslint](http://eslint.org/).

 - [x] Configure Eslint uging our [base config](https://github.com/LiskHQ/eslint-config-lisk-base). #259 
 - [x] Perform automatic fixings. #260 
 - Apply code changes and enhancements required to meet eslint rules:
    - [x] libs directory #262 
    - [x] api directory #266 
    - [x] utils directory #265 
    - [x] api sockets #273 
    - [x] api benchmarks #268 
    - [x] everything else except `src` directory #279 
    - [x] `src/components` directory #271 
    - [x] everything else in `src` directory #276

**Comment by alepop** [comment]
@karmacoma what kind of config file do I need to use in this project? from `lisk-nano` or `lisk-js`

**Comment by alihaghighatkhah** [comment]
@karmacoma @slaweet Since the changes `eslint` requires exceed 1K, I'd suggest focusing this ticket to automatically fixable errors and creating separate tickets for each of modules. This way we'll keep the number of the changed files minimum, reducing the chance of conflicts.

**Comment by karmacoma** [comment]
@reyraa Agree

**Comment by reyraa** [comment]
This issue is closed by #259 , #260  , #262 , #265 , #266  , #268 , #271 , #273 , #276 , #279
