### ISSUE TITLE
Update API requests for Lisk Core 1.0.0

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#145]
Update API requests to achieve compatibility with Lisk Core 1.0.0.

- [x] Update Api/accounts endpoints #287 https://github.com/LiskHQ/lisk-explorer/pull/288 #397 
- [x] Update Api/transactions endpoints #291 https://github.com/LiskHQ/lisk-explorer/pull/293 #398 
- [x] Update Api/blocks endpoints #290 https://github.com/LiskHQ/lisk-explorer/pull/298 #399 
- [x] Update Api/statistics endpoints #290 https://github.com/LiskHQ/lisk-explorer/issues/302 #400 
- [x] Update Api/search endpoints #303 https://github.com/LiskHQ/lisk-explorer/pull/305 #401 
- [x] Update Api/delegates endpoints #430 #431 
- [x] Update sockets/delegateMonitor.js #403 #437
