### ISSUE TITLE
Core 1.0 API alignment post-update bugs

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#465]
This ticket collects all backend bugs found after the API update.

- [x] Search by transaction ID #464 #471
- [x] Dockerfile & docker-compose config bug #504
- [x] forum.lisk.io delegateProposal removal #473
- [x] Block height is always equal to 1 #472
- [x] Delegates.getForged() -> using wrong API route, should be `/delegates/{address}/forging_statistics`
- [x] Add mapper for peers #497
- [x] Broken FreeGeoIP binding #517 
- [x] All Transactions tab only shows received transactions #499
- [x] Voters list not showing on delegate page #502
- [x] Votes list not showing on address page #501
- [x] Add mapper for peers #497
- [x] Top Accounts page not showing owner #490
- [x] Delegate page not showing data #484
- [x] Mapping stability error #523
- [x] Delegate Monitor: Delegate data missing #526
- [x] Delegate Monitor: Incorrect URLs in the latest votes #528
- [x] Delegate Monitor: Latest Votes list keep switching between username/address #544
- [x] Delegate Monitor: Always showing 0 delegates on standby #543
- [x] Network Monitor: Incorrect best block amount #547
- [x] Delegate Voters list not displaying known username #550
- [x] Latest Blocks list on the main page doesn't show delegate username #555
- [x] Network Monitor: Update table sorting #560
- [x] Market Watcher: N/A Num Trades #569
- [x] Market Watcher and Price Ticker stability bugs #545

Solving all the issues above is required for the next beta release of 2.0.0.
Further issues will be moved to the parent issue #559
