### ISSUE TITLE
Review and fix all API tests

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#470]
Before the release of Explorer 2.0.0 all functional tests should be reviewed.

Checklist:
- What that test actually do?
- Do we need this test?
- Is it stable, ie. not failing on Jenkins? If not, mark it unstable to avoid running on Jenkins.
- Can we improve that test somehow?

Known problems:
- [ ] No multisignature account tests
- [x] Missing votes and voters extensive checks
- [ ] Mock the 3rd party APIs (Bittrex, Poloniex, exchanges, etc.) #561
