### ISSUE TITLE
Minor frontend issues - Stage 1

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#558]
In order to release the new version, the following issues have to be solved:

### Severe
- [x] Latest transactions: (id, amount) should be changed to (sender w/address shortener, recipient w/address shortener, amount) (mobile) #626
- [x] Latest Blocks: (id, height) should be replaced with (height, transactions, delegate, forged) (mobile) #626
- [x] Transaction table component issues #599 

### Low
- [x] Final balance background (desktop) #628
- [x] Currency changer menu should be closed after a tap (mobile) #649
- [x] General: Search box requires additional click, inputbox should be active automatically #596
- [x] Address page: Sorting works, but the icon shows wrong sorting direction #599
- [x] Delegate Monitor: `Total forged` should be shown without decimal places #630

_Address summary: Known delegate name is not an active link (Chrome) or requires a double click (Firefox) #599_ -> described in #599
