### ISSUE TITLE
Prepare the codebase for the final release

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#559]
The following issues have to be solved before the final (stable) release of 2.x.

- [x] UI Update #508
- [x] Review types provided by the Explorer 2.x API #706

Low:

- [x] Block Page: Transactions pagination not working #556

Update tests: 

- [x] Review and fix all skipped API tests #470 
- [x] Update of 2.0.0 e2e tests #507
