### ISSUE TITLE
Merge fixes for 2.0.0 into 1.6.0

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#571]
The list of fixes that should be merged:

- [x] Market Watcher: N/A Num Trades #569 
- [x] Market Watcher and Price Ticker stability bugs #545
- [x] Invalid reverse DNS query crashes the process #540
- [x] Add comment with the application version to the HTML template #480
