### ISSUE TITLE
Merge fixes for 2.0.0 into 1.6.1

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#573]
The list of fixes that should be merged:

- [x] Remove the delegate proposal functionality #473 
- [x] Update Top Accounts #588
- [x] Jenkins Slack notifications #583
