### ISSUE TITLE
Transaction table component issues

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#599]
Current problems:

- [x] Inconsistent sorting direction is shown by the blue icon (M)
- [x] the icon copy to clipboard overlaps with a delegate name #604 
- [x] Columns mixed up #612
- [x] Show the date field in the tablet view (M)
- [x] The amount, confirmations should be aligned to the right (L) #632
- [x] Confirmed transaction should display a tick icon

_- delegate name does not act as a link -> it seems it was a link to the same page only_ 
_- All decimal points should be visible by default -> changed requirments in #632_
_- Monospace font for Trx ID, Sender, Rcp, Amount, Confirmations_ -> not needed, the current font looks ok
