### ISSUE TITLE
Minor frontend issues - Stage 2

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#600]
In order to release the new version, the following issues have to be solved:

### Severe

- [x] Delegate vote transaction should be displayed in the `Others` tab #652
- [x] Address: Transactions take too much space (mobile) (easy) #643
- [x] Network Monitor: To prevent problems with page scrolling, the map should react to multi-finger gestures only (mobile) #693 
- [x] Network Monitor: Page scrolling with a mouse scroll not possible over the world map area (desktop) #694

_- [ ] Transaction: Summary and Details have different styles (mobile / desktop)_

### Low

- [x] General: Trim floating points (confirm) #632
- [x] General: Search box should become an input field back on a desktop but an icon on mobile #669

_- [ ] General: Tablet mode shows the search icon in a wrong order_
