### ISSUE TITLE
Add support for leading markets' currencies 

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#726]
The following FIAT currencies should be supported by the backend:

- [x] US Dollar (USD)
- [x] Polish Zloty (PLN) #728
- [x] Japanese Yen (JPY) #730
- [x] British Pound (GBP) #729
- [x] Euro (EUR)
- [x] Chinese Yuan (CNY) #562
